version: '3.8'
services:
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres
   
  disturbutedcache:
    image: redis

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  baseketapi:
    image: ${DOCKER_REGISTRY-}baseketapi
    build:
      context: .
      dockerfile: Services/Basket/BaseketAPI/Dockerfile

  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/DiscountGrpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


 


