version: '3.8'
services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=myPosgres
      - POSTGRES_PASSWORD=myPostgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
           